[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

[profile.dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", branch = "main" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options